/* ============================================================
   Phoenix SRMPC — Solo Career: master track library
   One entry per circuit/venue, shared by every game in
   sc-gamedb.js (games reference tracks by name). Game-specific
   names (e.g. NR2003's "California Speedway") are separate
   entries on purpose, so each game shows the name you'll see
   in its own track menu.

   type codes (drive car-rating weights + incident rates):
     ss  superspeedway / drafting oval     ov  intermediate oval
     so  short oval                        rd  permanent road course
     st  street / temporary circuit        dt  dirt oval
     ry  rally stages                      rx  rallycross
     ar  derby arena                       f8  figure-8 / crossover
     kt  kart circuit                      hc  hill climb
   flags: n = night race by tradition, m = community mod/add-on
   ============================================================ */
'use strict';

(function (root) {
    const SC = root.SC = root.SC || {};

    // [name, type, lengthKm, country, flags]
    const RAW = [
        /* ---------- Europe: road ---------- */
        ['Silverstone', 'rd', 5.891, 'UK'],
        ['Silverstone International', 'rd', 2.978, 'UK'],
        ['Brands Hatch', 'rd', 3.908, 'UK'],
        ['Brands Hatch Indy', 'rd', 1.929, 'UK'],
        ['Donington Park', 'rd', 4.020, 'UK'],
        ['Oulton Park', 'rd', 4.307, 'UK'],
        ['Snetterton', 'rd', 4.779, 'UK'],
        ['Cadwell Park', 'rd', 3.494, 'UK'],
        ['Thruxton', 'rd', 3.792, 'UK'],
        ['Knockhill', 'rd', 2.092, 'UK'],
        ['Croft', 'rd', 3.420, 'UK'],
        ['Spa-Francorchamps', 'rd', 7.004, 'Belgium'],
        ['Zolder', 'rd', 4.011, 'Belgium'],
        ['Zandvoort', 'rd', 4.259, 'Netherlands'],
        ['Assen', 'rd', 4.555, 'Netherlands'],
        ['Monza', 'rd', 5.793, 'Italy'],
        ['Imola', 'rd', 4.909, 'Italy'],
        ['Mugello', 'rd', 5.245, 'Italy'],
        ['Misano', 'rd', 4.226, 'Italy'],
        ['Vallelunga', 'rd', 4.085, 'Italy'],
        ['Magione', 'rd', 2.507, 'Italy'],
        ['Enna-Pergusa', 'rd', 4.950, 'Italy'],
        ['Nürburgring GP', 'rd', 5.148, 'Germany'],
        ['Nürburgring Nordschleife', 'rd', 20.832, 'Germany'],
        ['Nürburgring 24h Layout', 'rd', 25.378, 'Germany'],
        ['Hockenheim', 'rd', 4.574, 'Germany'],
        ['Norisring', 'st', 2.300, 'Germany'],
        ['Lausitzring', 'rd', 3.478, 'Germany'],
        ['Oschersleben', 'rd', 3.696, 'Germany'],
        ['Sachsenring', 'rd', 3.645, 'Germany'],
        ['Bilster Berg', 'rd', 4.200, 'Germany'],
        ['Red Bull Ring', 'rd', 4.318, 'Austria'],
        ['A1-Ring', 'rd', 4.326, 'Austria'],
        ['Salzburgring', 'rd', 4.241, 'Austria'],
        ['Paul Ricard', 'rd', 5.842, 'France'],
        ['Magny-Cours', 'rd', 4.411, 'France'],
        ['Circuit de la Sarthe (Le Mans)', 'rd', 13.626, 'France'],
        ['Pau', 'st', 2.760, 'France'],
        ['Dijon-Prenois', 'rd', 3.801, 'France'],
        ['Rouen-les-Essarts', 'rd', 6.542, 'France'],
        ['Barcelona-Catalunya', 'rd', 4.657, 'Spain'],
        ['Jerez', 'rd', 4.428, 'Spain'],
        ['Valencia (Ricardo Tormo)', 'rd', 4.005, 'Spain'],
        ['Navarra', 'rd', 3.933, 'Spain'],
        ['MotorLand Aragón', 'rd', 5.078, 'Spain'],
        ['Estoril', 'rd', 4.182, 'Portugal'],
        ['Portimão', 'rd', 4.653, 'Portugal'],
        ['Porto (Boavista)', 'st', 4.800, 'Portugal'],
        ['Brno', 'rd', 5.403, 'Czechia'],
        ['Most', 'rd', 4.212, 'Czechia'],
        ['Slovakia Ring', 'rd', 5.922, 'Slovakia'],
        ['Hungaroring', 'rd', 4.381, 'Hungary'],
        ['Poznań', 'rd', 4.083, 'Poland'],
        ['Anderstorp', 'rd', 4.025, 'Sweden'],
        ['Knutstorp', 'rd', 2.067, 'Sweden'],
        ['Mantorp Park', 'rd', 3.106, 'Sweden'],
        ['Karlskoga', 'rd', 2.250, 'Sweden'],
        ['Falkenberg', 'rd', 2.664, 'Sweden'],
        ['Jyllandsringen', 'rd', 2.300, 'Denmark'],
        ['Moscow Raceway', 'rd', 3.931, 'Russia'],
        ['Istanbul Park', 'rd', 5.338, 'Turkey'],
        ['Monaco', 'st', 3.337, 'Monaco'],
        ['Azure Circuit', 'st', 3.340, 'Monaco'],
        ['Baku City Circuit', 'st', 6.003, 'Azerbaijan'],

        /* ---------- Middle East / Africa ---------- */
        ['Bahrain', 'rd', 5.412, 'Bahrain', 'n'],
        ['Jeddah Corniche', 'st', 6.174, 'Saudi Arabia', 'n'],
        ['Yas Marina', 'rd', 5.281, 'UAE', 'n'],
        ['Dubai Autodrome', 'rd', 5.390, 'UAE'],
        ['Lusail', 'rd', 5.419, 'Qatar', 'n'],
        ['Kyalami', 'rd', 4.529, 'South Africa'],

        /* ---------- Asia / Oceania ---------- */
        ['Suzuka', 'rd', 5.807, 'Japan'],
        ['Fuji Speedway', 'rd', 4.563, 'Japan'],
        ['Twin Ring Motegi', 'rd', 4.801, 'Japan'],
        ['Okayama', 'rd', 3.703, 'Japan'],
        ['Tsukuba', 'rd', 2.045, 'Japan'],
        ['Autopolis', 'rd', 4.674, 'Japan'],
        ['Sugo', 'rd', 3.586, 'Japan'],
        ['Shanghai', 'rd', 5.451, 'China'],
        ['Zhuhai', 'rd', 4.319, 'China'],
        ['Macau (Guia Circuit)', 'st', 6.120, 'Macau'],
        ['Sepang', 'rd', 5.543, 'Malaysia'],
        ['Chang International (Buriram)', 'rd', 4.554, 'Thailand'],
        ['Marina Bay', 'st', 4.940, 'Singapore', 'n'],
        ['Albert Park', 'st', 5.278, 'Australia'],
        ['Mount Panorama (Bathurst)', 'rd', 6.213, 'Australia'],
        ['Phillip Island', 'rd', 4.445, 'Australia'],
        ['Sandown', 'rd', 3.104, 'Australia'],
        ['Adelaide Street Circuit', 'st', 3.780, 'Australia'],
        ['Hampton Downs', 'rd', 3.800, 'New Zealand'],
        ['Ruapuna', 'rd', 3.330, 'New Zealand'],

        /* ---------- South America ---------- */
        ['Interlagos', 'rd', 4.309, 'Brazil'],
        ['Goiânia', 'rd', 3.835, 'Brazil'],
        ['Curitiba', 'rd', 3.695, 'Brazil'],
        ['Londrina', 'rd', 3.145, 'Brazil'],
        ['Cascavel', 'rd', 3.302, 'Brazil'],
        ['Velopark', 'rd', 2.278, 'Brazil'],
        ['Campo Grande', 'rd', 3.433, 'Brazil'],
        ['Santa Cruz do Sul', 'rd', 3.531, 'Brazil'],
        ['Tarumã', 'rd', 3.067, 'Brazil'],
        ['Guaporé', 'rd', 3.080, 'Brazil'],
        ['Brasília', 'rd', 5.476, 'Brazil'],
        ['Jacarepaguá', 'rd', 5.031, 'Brazil'],
        ['Velo Città', 'rd', 3.444, 'Brazil'],
        ['Buenos Aires', 'rd', 4.259, 'Argentina'],
        ['Termas de Río Hondo', 'rd', 4.806, 'Argentina'],

        /* ---------- North America: road & street ---------- */
        ['Circuit of the Americas', 'rd', 5.513, 'USA'],
        ['Watkins Glen', 'rd', 5.430, 'USA'],
        ['Laguna Seca', 'rd', 3.602, 'USA'],
        ['Road America', 'rd', 6.515, 'USA'],
        ['Road Atlanta', 'rd', 4.088, 'USA'],
        ['Sebring', 'rd', 6.019, 'USA'],
        ['Lime Rock Park', 'rd', 2.459, 'USA'],
        ['Mid-Ohio', 'rd', 3.634, 'USA'],
        ['Virginia International Raceway', 'rd', 5.263, 'USA'],
        ['Barber Motorsports Park', 'rd', 3.830, 'USA'],
        ['Sonoma Raceway', 'rd', 3.990, 'USA'],
        ['Infineon Raceway (Sears Point)', 'rd', 3.220, 'USA'],
        ['Summit Point', 'rd', 3.200, 'USA'],
        ['Portland International Raceway', 'rd', 3.160, 'USA'],
        ['Willow Springs', 'rd', 4.020, 'USA'],
        ['Daytona Road Course', 'rd', 5.730, 'USA'],
        ['Indianapolis Road Course', 'rd', 3.925, 'USA'],
        ['Charlotte Roval', 'rd', 3.700, 'USA'],
        ['Long Beach', 'st', 3.167, 'USA'],
        ['Detroit Street Circuit', 'st', 2.650, 'USA'],
        ['Chicago Street Course', 'st', 3.540, 'USA'],
        ['San Diego Street Course', 'st', 3.300, 'USA'],
        ['St. Petersburg', 'st', 2.900, 'USA'],
        ['Miami International Autodrome', 'st', 5.412, 'USA'],
        ['Las Vegas Strip Circuit', 'st', 6.201, 'USA', 'n'],
        ['Canadian Tire Motorsport Park', 'rd', 3.957, 'Canada'],
        ['Circuit Gilles Villeneuve', 'rd', 4.361, 'Canada'],
        ['Mexico City (Hermanos Rodríguez)', 'rd', 4.304, 'Mexico'],
        ['Puebla', 'rd', 3.500, 'Mexico'],

        /* ---------- Ovals: superspeedways & intermediates ---------- */
        ['Daytona International Speedway', 'ss', 4.023, 'USA'],
        ['Talladega Superspeedway', 'ss', 4.281, 'USA'],
        ['EchoPark Speedway (Atlanta)', 'ss', 2.478, 'USA'],
        ['Atlanta Motor Speedway', 'ov', 2.478, 'USA'],
        ['Charlotte Motor Speedway', 'ov', 2.414, 'USA', 'n'],
        ["Lowe's Motor Speedway", 'ov', 2.414, 'USA', 'n'],
        ['Texas Motor Speedway', 'ov', 2.414, 'USA'],
        ['Las Vegas Motor Speedway', 'ov', 2.414, 'USA'],
        ['Kansas Speedway', 'ov', 2.414, 'USA'],
        ['Homestead-Miami Speedway', 'ov', 2.414, 'USA'],
        ['Chicagoland Speedway', 'ov', 2.414, 'USA'],
        ['Kentucky Speedway', 'ov', 2.414, 'USA', 'n'],
        ['Michigan International Speedway', 'ov', 3.219, 'USA'],
        ['Auto Club Speedway', 'ov', 3.219, 'USA'],
        ['California Speedway', 'ov', 3.219, 'USA'],
        ['Pocono Raceway', 'ov', 4.023, 'USA'],
        ['Indianapolis Motor Speedway', 'ov', 4.023, 'USA'],
        ['Darlington Raceway', 'ov', 2.213, 'USA'],
        ['Nashville Superspeedway', 'ov', 2.145, 'USA', 'n'],
        ['Dover Motor Speedway', 'ov', 1.609, 'USA'],
        ['Dover International Speedway', 'ov', 1.609, 'USA'],
        ['Phoenix Raceway', 'ov', 1.644, 'USA'],
        ['Phoenix International Raceway', 'ov', 1.609, 'USA'],
        ['World Wide Technology Raceway (Gateway)', 'ov', 2.012, 'USA'],
        ['Gateway International Raceway', 'ov', 2.012, 'USA', 'm'],
        ['New Hampshire Motor Speedway', 'ov', 1.703, 'USA'],
        ['New Hampshire International Speedway', 'ov', 1.703, 'USA'],
        ['Rockingham Speedway', 'ov', 1.636, 'USA'],
        ['North Carolina Speedway (Rockingham)', 'ov', 1.636, 'USA'],
        ['Milwaukee Mile', 'ov', 1.609, 'USA'],
        ['Pikes Peak International Raceway', 'ov', 1.609, 'USA', 'm'],
        ['Texas World Speedway', 'ov', 3.219, 'USA', 'm'],

        /* ---------- Short ovals ---------- */
        ['Bristol Motor Speedway', 'so', 0.858, 'USA', 'n'],
        ['Martinsville Speedway', 'so', 0.847, 'USA'],
        ['Richmond Raceway', 'so', 1.207, 'USA', 'n'],
        ['Richmond International Raceway', 'so', 1.207, 'USA', 'n'],
        ['Iowa Speedway', 'so', 1.408, 'USA'],
        ['North Wilkesboro Speedway', 'so', 1.006, 'USA', 'n'],
        ['Nashville Fairgrounds Speedway', 'so', 0.959, 'USA', 'n'],
        ['Memphis Motorsports Park', 'so', 1.207, 'USA', 'm'],
        ['Lucas Oil Indianapolis Raceway Park', 'so', 1.104, 'USA', 'n'],
        ['Bowman Gray Stadium', 'so', 0.402, 'USA', 'n'],
        ['South Boston Speedway', 'so', 0.644, 'USA', 'n'],
        ['Hickory Motor Speedway', 'so', 0.584, 'USA', 'n'],
        ['Myrtle Beach Speedway', 'so', 0.866, 'USA', 'n'],
        ['Langley Speedway', 'so', 0.636, 'USA', 'n'],
        ['Irwindale Speedway', 'so', 0.805, 'USA', 'n'],
        ['Toledo Speedway', 'so', 0.805, 'USA', 'n'],
        ['Salem Speedway', 'so', 0.893, 'USA'],
        ['Berlin Raceway', 'so', 0.704, 'USA', 'n'],
        ['Five Flags Speedway', 'so', 0.805, 'USA', 'n'],
        ['Mesa Marin Raceway', 'so', 0.805, 'USA', 'n'],
        ['Stafford Motor Speedway', 'so', 0.805, 'USA', 'n'],
        ['Thompson Speedway', 'so', 1.006, 'USA'],
        ['Oxford Plains Speedway', 'so', 0.604, 'USA'],
        ['Lanier National Speedway', 'so', 0.604, 'USA', 'n'],
        ['New Smyrna Speedway', 'so', 0.772, 'USA', 'n'],
        ['Concord Speedway', 'so', 0.805, 'USA', 'n'],
        ['Kern County Raceway Park', 'so', 0.805, 'USA', 'n'],
        ['Joesville Speedway', 'so', 1.100, 'USA'],
        ['Eaglerock Speedway', 'so', 1.610, 'USA'],

        /* ---------- Dirt ovals ---------- */
        ['Eldora Speedway', 'dt', 0.805, 'USA', 'n'],
        ['Knoxville Raceway', 'dt', 0.805, 'USA', 'n'],
        ['Williams Grove Speedway', 'dt', 0.805, 'USA', 'n'],
        ['Volusia Speedway Park', 'dt', 0.805, 'USA', 'n'],
        ['Lincoln Speedway', 'dt', 0.644, 'USA', 'n'],
        ['Port Royal Speedway', 'dt', 0.805, 'USA', 'n'],
        ['Weedsport Speedway', 'dt', 0.604, 'USA', 'n'],
        ['Cedar Lake Speedway', 'dt', 0.604, 'USA', 'n'],
        ['Fairbury Speedway', 'dt', 0.402, 'USA', 'n'],
        ['Kokomo Speedway', 'dt', 0.402, 'USA', 'n'],
        ['Limaland Motorsports Park', 'dt', 0.402, 'USA', 'n'],
        ['USA International Speedway', 'dt', 0.805, 'USA', 'n'],
        ['Federated Auto Parts Raceway at I-55', 'dt', 0.543, 'USA', 'n'],
        ['Charlotte Dirt Track', 'dt', 0.644, 'USA', 'n'],
        ['Bristol Dirt', 'dt', 0.858, 'USA', 'n'],
        ['Atomic Speedway', 'dt', 0.604, 'USA', 'n'],
        ['Tulsa Expo Raceway (Chili Bowl)', 'dt', 0.402, 'USA', 'n'],
        ["Huset's Speedway", 'dt', 0.604, 'USA', 'n'],
        ['DuQuoin State Fairgrounds', 'dt', 1.609, 'USA'],
        ['Illinois State Fairgrounds (Springfield)', 'dt', 1.609, 'USA'],
        ['Canyon Ridge Dirt Oval', 'dt', 0.644, 'USA'],
        ['Riverbend Dirt Speedway', 'dt', 0.604, 'USA'],

        /* ---------- Rally (events, not circuits) ---------- */
        ['Rally Monte-Carlo', 'ry', 18, 'Monaco'],
        ['Rally Sweden', 'ry', 18, 'Sweden'],
        ['Rally Mexico', 'ry', 18, 'Mexico'],
        ['Croatia Rally', 'ry', 18, 'Croatia'],
        ['Rally de Portugal', 'ry', 18, 'Portugal'],
        ['Rally Italia Sardegna', 'ry', 18, 'Italy'],
        ['Safari Rally Kenya', 'ry', 18, 'Kenya'],
        ['Rally Estonia', 'ry', 18, 'Estonia'],
        ['Rally Finland', 'ry', 18, 'Finland'],
        ['Acropolis Rally Greece', 'ry', 18, 'Greece'],
        ['Rally Chile', 'ry', 18, 'Chile'],
        ['Central European Rally', 'ry', 18, 'Germany'],
        ['Rally Japan', 'ry', 18, 'Japan'],
        ['Rally Poland', 'ry', 18, 'Poland'],
        ['Rally Latvia', 'ry', 18, 'Latvia'],
        ['Rally New Zealand', 'ry', 18, 'New Zealand'],
        ['Rally Spain', 'ry', 18, 'Spain'],
        ['Rally Argentina', 'ry', 18, 'Argentina'],
        ['Rally Australia', 'ry', 18, 'Australia'],
        ['Rally USA (New England)', 'ry', 18, 'USA'],
        ['Wales Rally GB', 'ry', 18, 'UK'],
        ['Rally Germany', 'ry', 18, 'Germany'],
        ['Rally Scotland', 'ry', 18, 'UK'],
        ['Rally Scandia', 'ry', 18, 'Norway'],
        ['Rally Mediterraneo', 'ry', 18, 'Italy'],
        ['Rally Pacifico', 'ry', 18, 'Indonesia'],
        ['Rally Iberia', 'ry', 18, 'Spain'],
        ['Rally Oceania', 'ry', 18, 'New Zealand'],

        /* ---------- Rallycross ---------- */
        ['Lydden Hill', 'rx', 1.000, 'UK'],
        ['Höljes', 'rx', 1.200, 'Sweden'],
        ['Lohéac', 'rx', 1.100, 'France'],
        ['Hell (Lånkebanen)', 'rx', 1.100, 'Norway'],
        ['Mettet', 'rx', 1.100, 'Belgium'],
        ['Montalegre', 'rx', 1.100, 'Portugal'],
        ['Barcelona Rallycross', 'rx', 1.100, 'Spain'],
        ['Riga (Biķernieki)', 'rx', 1.300, 'Latvia'],
        ['Silverstone Rallycross', 'rx', 1.000, 'UK'],
        ['Trois-Rivières', 'rx', 1.000, 'Canada'],

        /* ---------- Karting ---------- */
        ['Glencairn', 'kt', 1.100, 'UK'],
        ['Summerton', 'kt', 1.000, 'UK'],
        ['Chesterfield Karting', 'kt', 1.200, 'UK'],
        ['Buskerud Kart', 'kt', 1.100, 'Norway'],
        ['Granja Viana Kart', 'kt', 1.100, 'Brazil'],
        ['Speedland Kart', 'kt', 1.000, 'Brazil'],
        ['PF International', 'kt', 1.382, 'UK'],
        ['South Garda Karting (Lonato)', 'kt', 1.200, 'Italy'],

        /* ---------- Fictional / game-original circuits ---------- */
        ['Black Cat County', 'rd', 3.960, 'USA'],
        ['Highlands', 'rd', 5.800, 'UK'],
        ['Trento-Bondone Hill Climb', 'hc', 17.300, 'Italy'],
        ['California Highway', 'rd', 12.000, 'USA'],
        ['Azure Coast', 'st', 8.000, 'France'],
        ['Sakitto', 'rd', 5.000, 'Japan'],
        ['Bannochbrae Road Circuit', 'rd', 8.000, 'UK'],
        ['Mojave Test Track', 'rd', 4.000, 'USA'],
        ['Mills Metropark', 'rd', 3.200, 'USA'],
        ['Toban Raceway Park', 'rd', 3.800, 'USA'],
        ['Lienz Festival', 'st', 3.000, 'Austria'],
        ['Orchard Lake', 'rd', 3.500, 'USA'],
        ['Essington Park', 'rd', 3.400, 'UK'],
        ['Autodrome Lago Maggiore', 'rd', 5.809, 'Italy'],
        ['Dragon Trail', 'rd', 5.209, 'Croatia'],
        ['Trial Mountain Circuit', 'rd', 5.990, 'USA'],
        ['Deep Forest Raceway', 'rd', 4.550, 'Switzerland'],
        ['High Speed Ring', 'rd', 4.000, 'Japan'],
        ['Grand Valley Highway', 'rd', 5.200, 'USA'],
        ['Tokyo Expressway', 'st', 7.300, 'Japan'],
        ['Kyoto Driving Park', 'rd', 4.910, 'Japan'],
        ['Alsace Village', 'st', 5.420, 'France'],
        ['Sardegna Road Track', 'rd', 5.110, 'Italy'],
        ["Fisherman's Ranch", 'ry', 6.650, 'USA'],
        ['Colorado Springs Lake', 'ry', 4.050, 'USA'],
        ['Special Stage Route X', 'ss', 30.280, 'USA'],
        ['Maple Valley', 'rd', 4.200, 'USA'],
        ['Grand Oak Raceway', 'rd', 4.300, 'USA'],
        ['Hakone Circuit', 'rd', 5.100, 'Japan'],
        ['West Coast USA', 'rd', 3.000, 'USA'],
        ['Italy (BeamNG)', 'rd', 4.000, 'Italy'],
        ['Utah', 'ry', 6.000, 'USA'],
        ['Jungle Rock Island', 'rd', 3.500, 'Tropics'],
        ['Automation Test Track', 'rd', 3.600, 'USA'],
        ['Hirochi Raceway', 'rd', 3.800, 'Japan'],
        ['East Coast USA', 'rd', 3.000, 'USA'],
        ['Johnson Valley', 'ry', 8.000, 'USA'],
        ['Derby Arena', 'ar', 0.300, 'USA'],
        ['Gridmap Oval', 'so', 0.800, 'USA'],

        /* ---------- Wreckfest ---------- */
        ['Big Valley Speedway', 'so', 0.700, 'USA'],
        ['Bloomfield Speedway', 'dt', 0.600, 'USA'],
        ['Bonebreaker Valley', 'ar', 0.400, 'USA'],
        ['Crash Canyon', 'ar', 0.400, 'USA'],
        ['Deathloop', 'f8', 0.700, 'USA'],
        ['Drytown Desert Circuit', 'dt', 1.300, 'USA'],
        ['Eagles Peak Motorpark', 'rd', 1.600, 'USA'],
        ['Espedalen Raceway', 'dt', 1.300, 'Finland'],
        ['Fire Rock Raceway', 'so', 0.900, 'USA'],
        ['Firwood Motocenter', 'rd', 1.500, 'Finland'],
        ['Hillstreet Circuit', 'st', 1.400, 'USA'],
        ['Kingston Raceway', 'rd', 1.700, 'USA'],
        ['Madman Stadium', 'f8', 0.500, 'USA'],
        ['Motorcity Circuit', 'st', 1.600, 'USA'],
        ['Northland Raceway', 'rd', 1.500, 'Finland'],
        ['Pinehills Raceway', 'rd', 1.600, 'USA'],
        ['Rattlesnake Racepark', 'rd', 1.700, 'USA'],
        ['Rockfield Roughspot', 'dt', 1.200, 'UK'],
        ['Sandstone Raceway', 'rd', 1.800, 'USA'],
        ['Savolax Sandpit', 'dt', 1.100, 'Finland'],
        ['Speedbowl', 'so', 0.600, 'USA'],
        ['Vale Falls Circuit', 'rd', 1.800, 'USA'],
        ['Glendale Countryside', 'dt', 1.400, 'USA'],
        ['Maasten Motoring', 'rd', 1.500, 'Finland'],
        ['Mudford Motorpark', 'dt', 1.200, 'UK'],
        ['Thunderbowl Arena', 'ar', 0.350, 'USA'],

        /* ---------- Wreckfest 2 (Early Access — rename to match your build) ---------- */
        ['WF2 Speedway Oval', 'so', 0.700, 'USA'],
        ['WF2 Figure-8 Stadium', 'f8', 0.500, 'USA'],
        ['WF2 Dirt Circuit', 'dt', 1.300, 'USA'],
        ['WF2 Tarmac Circuit', 'rd', 1.600, 'USA'],
        ['WF2 Mixed-Surface Circuit', 'rx', 1.500, 'Finland'],
        ['WF2 Demolition Arena', 'ar', 0.400, 'USA'],
        ['WF2 Gravel Pit', 'dt', 1.100, 'Finland'],
        ['WF2 Harbor Circuit', 'st', 1.700, 'USA'],
        ['WF2 Forest Rallycross', 'rx', 1.400, 'Finland'],
        ['WF2 Canyon Circuit', 'rd', 1.900, 'USA']
    ];

    const TRACKS = {};
    RAW.forEach(([name, type, km, country, flags]) => {
        TRACKS[name] = { name, type, km, country, night: /n/.test(flags || ''), mod: /m/.test(flags || '') };
    });

    // Per track-type modelling: how much each car area matters there, the
    // base incident/DNF rate of the discipline, and a display label.
    const TRACK_TYPES = {
        ss: { label: 'Superspeedway', icon: '🌀', weights: { engine: 0.55, aero: 0.35, chassis: 0.10 }, dnf: 0.13 },
        ov: { label: 'Intermediate oval', icon: '⭕', weights: { engine: 0.40, aero: 0.35, chassis: 0.25 }, dnf: 0.08 },
        so: { label: 'Short oval', icon: '🔄', weights: { engine: 0.20, aero: 0.10, chassis: 0.70 }, dnf: 0.08 },
        rd: { label: 'Road course', icon: '🛣️', weights: { engine: 0.30, aero: 0.35, chassis: 0.35 }, dnf: 0.07 },
        st: { label: 'Street circuit', icon: '🏙️', weights: { engine: 0.20, aero: 0.25, chassis: 0.55 }, dnf: 0.12 },
        dt: { label: 'Dirt oval', icon: '🟤', weights: { engine: 0.35, aero: 0.05, chassis: 0.60 }, dnf: 0.11 },
        ry: { label: 'Rally', icon: '🌲', weights: { engine: 0.30, aero: 0.05, chassis: 0.65 }, dnf: 0.12 },
        rx: { label: 'Rallycross', icon: '🪨', weights: { engine: 0.35, aero: 0.05, chassis: 0.60 }, dnf: 0.09 },
        ar: { label: 'Derby arena', icon: '💥', weights: { engine: 0.20, aero: 0.00, chassis: 0.80 }, dnf: 0.00 },
        f8: { label: 'Figure-8', icon: '♾️', weights: { engine: 0.25, aero: 0.00, chassis: 0.75 }, dnf: 0.22 },
        kt: { label: 'Kart circuit', icon: '🛞', weights: { engine: 0.30, aero: 0.00, chassis: 0.70 }, dnf: 0.05 },
        hc: { label: 'Hill climb', icon: '⛰️', weights: { engine: 0.40, aero: 0.20, chassis: 0.40 }, dnf: 0.06 }
    };

    // Rough odds of rain by country (drives the "suggested weather" line).
    const RAIN = {
        UK: 0.32, Belgium: 0.35, Netherlands: 0.28, Germany: 0.24, Austria: 0.22, France: 0.18, Italy: 0.15,
        Spain: 0.08, Portugal: 0.1, Japan: 0.25, Brazil: 0.25, Malaysia: 0.35, Singapore: 0.2, China: 0.18,
        Australia: 0.15, 'New Zealand': 0.28, USA: 0.12, Canada: 0.2, Sweden: 0.25, Finland: 0.25, Norway: 0.3,
        Denmark: 0.3, Hungary: 0.14, Czechia: 0.2, Slovakia: 0.2, Poland: 0.22, Russia: 0.2, Turkey: 0.1,
        Mexico: 0.12, Argentina: 0.15, 'South Africa': 0.12, Bahrain: 0.01, 'Saudi Arabia': 0.01, UAE: 0.01,
        Qatar: 0.01, Kenya: 0.2, Monaco: 0.12, Azerbaijan: 0.08, Thailand: 0.3, Macau: 0.2
    };

    function track(name) {
        return TRACKS[name] || { name, type: 'rd', km: 4, country: '', night: false, mod: false, custom: true };
    }

    SC.TRACKS = TRACKS;
    SC.TRACK_TYPES = TRACK_TYPES;
    SC.RAIN = RAIN;
    SC.track = track;
})(typeof window !== 'undefined' ? window : globalThis);
